language: node_js
node_js: node
branches:
  only:
    - master
    - develop
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install: yarn --frozen-lockfile
script:
  - yarn lint
  - yarn test
cache:
  yarn: true
  directories:
    - node_modules
